##======================================================================================================================
## FLUXION - Post-Modern Automatic Derivation
## Copyright : FLUXION Contributors & Maintainers
## SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: FLUXION Integration Tests
on:
  push:
    branches:
      - main

concurrency:
  group: fluxion-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:

  install:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v9
    strategy:
      fail-fast: false

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Install FLUXION from checkout
        run: |
          mkdir build && cd build
          cmake -G Ninja .. -DFLUXION_BUILD_TEST=OFF
          ninja install
      - name: Run Sample CMake
        run: |
          mkdir install && cd install
          cmake ../test/integration/install-test -G Ninja
          ninja test_fluxion && ctest -R ^test_fluxion* --verbose

  fetch-content:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Run Sample CMake
        run: |
          git config --global --add safe.directory /__w/fluxion/fluxion
          mkdir install && cd install
          cmake ../test/integration/fetch-test -G Ninja -DGIT_BRANCH=${BRANCH_NAME} -DFLUXION_BUILD_TEST=OFF
          ninja test_fluxion && ctest -R ^test_fluxion* --verbose

  cpm:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v6
    strategy:
      fail-fast: false

    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Run Sample CMake
        run: |
          git config --global --add safe.directory /__w/fluxion/fluxion
          mkdir install && cd install
          cmake ../test/integration/cpm-test -G Ninja -DGIT_BRANCH=${BRANCH_NAME}
          ninja test_fluxion && ctest -R ^test_fluxion* --verbose
