##======================================================================================================================
## FLUXION - Post-Modern Automatic Derivation
## Copyright : FLUXION Contributors & Maintainers
## SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: FLUXION Unit Testing
on:
  pull_request:
    branches:
      - main

concurrency:
  group: fluxion-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/jfalcou/compilers:v9
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { compiler: g++     , opts: "-O3 -DNDEBUG"                       }
        - { compiler: clang++ , opts: "-O3 -DNDEBUG"                       }
        - { compiler: g++     , opts: "-O3 -DNDEBUG -mavx2"                }
        - { compiler: clang++ , opts: "-O3 -DNDEBUG -mavx2"                }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4
      - name: Running CMake for ${{ matrix.cfg.compiler }} with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -G Ninja -DCMAKE_CXX_COMPILER=${{ matrix.cfg.compiler }} -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}"
      - name: Running Unit Tests
        run:  cd build && ninja fluxion-test -j 8 && ctest --output-on-failure -j 8

  macosx:
    runs-on: [macos-14]
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { opts: -O0                                 , linker:                 }
        - { opts: "-O0 -stdlib=libc++"                , linker: -stdlib=libc++  }
        - { opts: "-O3 -flto -DNDEBUG"                , linker:                 }
        - { opts: "-O3 -flto -DNDEBUG -stdlib=libc++" , linker: -stdlib=libc++  }
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v4
      - name: Running CMake for clang++ with ${{ matrix.cfg.opts }}
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="${{ matrix.cfg.opts }}"  -DCMAKE_EXE_LINKER_FLAGS=${{ matrix.cfg.linker }}
      - name: Running Unit Tests
        run:  cd build && make fluxion-test -j 2 && ctest --output-on-failure -j 2
